<!doctype html>
<html lang="en>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>

  <style type="text/css">
    @media only screen and (min-width: 620px) {
      .u-row {
        width: 600px !important;
      }

      .u-row .u-col {
        vertical-align: top;
      }

      .u-row .u-col-100 {
        width: 600px !important;
      }

    }

    @media (max-width: 620px) {
      .u-row-container {
        max-width: 100% !important;
        padding-left: 0px !important;
        padding-right: 0px !important;
      }

      .u-row .u-col {
        min-width: 320px !important;
        max-width: 100% !important;
        display: block !important;
      }

      .u-row {
        width: calc(100% - 40px) !important;
      }

      .u-col {
        width: 100% !important;
      }

      .u-col>div {
        margin: 0 auto;
      }
    }

    body {
      margin: 0;
      padding: 0;
    }

    table,
    tr,
    td {
      vertical-align: top;
      border-collapse: collapse;
    }

    p {
      margin: 0;
    }

    .ie-container table,
    .mso-container table {
      table-layout: fixed;
    }

    * {
      line-height: inherit;
    }

    a[x-apple-data-detectors='true'] {
      color: inherit !important;
      text-decoration: none !important;
    }

    table,
    td {
      color: #000000;
    }

    a {
      color: #0000ee;
      text-decoration: underline;
    }

    @media (max-width: 480px) {
      #u_content_heading_1 .v-container-padding-padding {
        padding: 40px 10px 10px !important;
      }

      #u_content_heading_1 .v-font-size {
        font-size: 26px !important;
      }

      #u_content_image_1 .v-container-padding-padding {
        padding: 15px 10px 30px !important;
      }

      #u_content_image_1 .v-src-width {
        width: auto !important;
      }

      #u_content_image_1 .v-src-max-width {
        max-width: 100% !important;
      }

      #u_content_text_1 .v-container-padding-padding {
        padding: 25px 30px 10px !important;
      }

      #u_content_text_1 .v-text-align {
        text-align: center !important;
      }

      #u_content_button_1 .v-container-padding-padding {
        padding: 10px 10px 35px !important;
      }

      #u_content_button_1 .v-size-width {
        width: 60% !important;
      }

      #u_content_button_1 .v-text-align {
        text-align: center !important;
      }

      #u_content_heading_2 .v-container-padding-padding {
        padding: 10px 30px 15px !important;
      }

      #u_content_heading_2 .v-text-align {
        text-align: center !important;
      }

      #u_content_text_3 .v-container-padding-padding {
        padding: 0px 30px 60px !important;
      }

      #u_content_text_3 .v-text-align {
        text-align: center !important;
      }

      #u_content_text_3 .v-line-height {
        line-height: 160% !important;
      }
    }
  </style>



  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700&display=swap" rel="stylesheet" type="text/css">

</head>

<body class="clean-body u_body"
  style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #ffffff;color: #000000">
  <table
    style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #ffffff;width:100%"
    cellpadding="0" cellspacing="0">
    <tbody>
      <tr style="vertical-align: top">
        <td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top">
          <div class="u-row-container" style="padding: 0px;background-color: #fff;">
            <div class="u-row"
              style="Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;">
              <div
                style="border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;">
                <div class="u-col u-col-100"
                  style="max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;">
                  <div style="background: linear-gradient(90deg,#8bd9f8,#e3f5fc);;height: 100%;width: 100% !important;">
                    <div
                      style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;">
                      <table id="u_content_heading_1" style="font-family:'Rubik',sans-serif;" role="presentation"
                        cellpadding="0" cellspacing="0" width="100%" border="0">
                        <tbody>
                          <tr>
                            <td class="v-container-padding-padding"
                              style="overflow-wrap:break-word;word-break:break-word;padding:50px 10px 10px;font-family:'Rubik',sans-serif;"
                              align="left">
                              <h1 class="v-text-align v-line-height v-font-size"
                                style="margin: 0px; line-height: 110%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: 'Rubik',sans-serif; font-size: 30px;">
                                <strong>TALENTING TIENE UN AVISO IMPORTANTE PARA TI</strong>
                              </h1>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                      <table id="u_content_image_1" style="font-family:'Rubik',sans-serif;" role="presentation"
                        cellpadding="0" cellspacing="0" width="100%" border="0">
                        <tbody>
                          <tr>
                            <td class="v-container-padding-padding"
                              style="overflow-wrap:break-word;word-break:break-word;padding:30px 0px;font-family:'Rubik',sans-serif;"
                              align="left">
                              <table width="100%" cellpadding="0" cellspacing="0" border="0">
                                <tr>
                                  <td class="v-text-align" style="padding-right: 0px;padding-left: 0px;" align="center">
                                    <img align="center" border="0"
                                      src="https://parafrasear.es/wp-content/uploads/2022/02/Gramatical-Corrector-768x761.png.webp"
                                      alt="Illustration" title="Illustration"
                                      style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 600px;"
                                      width="600" class="v-src-width v-src-max-width" />
                                  </td>
                                </tr>
                              </table>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="u-row-container" style="padding: 0px;background-color: transparent">
            <div class="u-row"
              style="Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;">
              <div
                style="border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;">
                <div class="u-col u-col-100"
                  style="max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;">
                  <div
                    style="background-color: #ffffff;height: 100%;width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;">
                    <div
                      style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;">
                      <table id="u_content_text_1" style="font-family:'Rubik',sans-serif;" role="presentation"
                        cellpadding="0" cellspacing="0" width="100%" border="0">
                        <tbody>
                          <tr>
                            <td class="v-container-padding-padding"
                              style="overflow-wrap:break-word;word-break:break-word;padding:60px 30px 20px;font-family:'Rubik',sans-serif;"
                              align="left">
                              <div class="v-text-align v-line-height"
                                style="line-height: 160%; text-align: justify; word-wrap: break-word;">
                                <p style="font-size: 14px; line-height: 160%;"><span
                                    style="font-size: 16px; line-height: 25.6px;"><strong>¡Hola Ulises!</strong></span>
                                </p>
                                <p style="font-size: 14px; line-height: 160%;"> </p>
                                <p style="font-size: 14px; line-height: 160%;">En talenting lamentamos informarte que no
                                  has sido seleccionado para el trabajo que has postulado. Por ello te invitamos a
                                  entrar a nuestro sitio para seguir explorando alternativas.</p>
                              </div>

                            </td>
                          </tr>
                        </tbody>
                      </table>
                      <table id="u_content_button_1" style="font-family:'Rubik',sans-serif;" role="presentation"
                        cellpadding="0" cellspacing="0" width="100%" border="0">
                        <tbody>
                          <tr>
                            <td class="v-container-padding-padding"
                              style="overflow-wrap:break-word;word-break:break-word;padding:10px 10px 25px 30px;font-family:'Rubik',sans-serif;"
                              align="left">
                            </td>
                          </tr>
                        </tbody>
                      </table>
                      <table id="u_content_heading_2" style="font-family:'Rubik',sans-serif;" role="presentation"
                        cellpadding="0" cellspacing="0" width="100%" border="0">
                        <tbody>
                          <tr>
                            <td class="v-container-padding-padding"
                              style="overflow-wrap:break-word;word-break:break-word;padding:10px 30px 5px;font-family:'Rubik',sans-serif;"
                              align="left">
                              <h1 class="v-text-align v-line-height v-font-size"
                                style="margin: 0px; line-height: 140%; text-align: left; word-wrap: break-word; font-weight: normal; font-family: 'Rubik',sans-serif; font-size: 16px;">
                                <strong>Click en el boton para conluir con el proceso:</strong>
                              </h1>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                      <table id="u_content_text_3" style="font-family:'Rubik',sans-serif;" role="presentation"
                        cellpadding="0" cellspacing="0" width="100%" border="0">
                        <tbody>
                          <tr>
                            <td class="v-container-padding-padding"
                              style="overflow-wrap:break-word;word-break:break-word;padding:0px 10px 60px 30px;font-family:'Rubik',sans-serif;"
                              align="left">
                              <div class="v-text-align v-line-height"
                                style="line-height: 160%; text-align: justify; word-wrap: break-word;">
                                <a href="https://www.google.com" target="_blank" class="v-size-width"
                                  style="box-sizing: border-box;display: inline-block;font-family:'Rubik',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #ffffff; background-color: #805997; border-radius: 4px;-webkit-border-radius: 4px; -moz-border-radius: 4px; width:39%; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;">
                                  <span class="v-line-height"
                                    style="display:block;padding:10px 20px;line-height:120%;"><strong><span
                                        style="font-size: 14px; line-height: 16.8px;">Talenting</span></strong></span>
                                </a>
                              </div>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="u-row-container" style="padding: 0px;background-color: #fff;">
            <div class="u-row"
              style="Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;">
              <div
                style="border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;">
                <div class="u-col u-col-100"
                  style="max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;">
                  <div
                    style="background: linear-gradient(90deg,#8bd9f8,#e3f5fc);;height: 100%;width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;">
                    <div
                      style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;">
                      <table style="font-family:'Rubik',sans-serif;" role="presentation" cellpadding="0" cellspacing="0"
                        width="100%" border="0">
                        <tbody>
                          <tr>
                            <td class="v-container-padding-padding"
                              style="overflow-wrap:break-word;word-break:break-word;padding:35px 10px 10px;font-family:'Rubik',sans-serif;"
                              align="left">
                            </td>
                          </tr>
                        </tbody>
                      </table>
                      <table style="font-family:'Rubik',sans-serif;" role="presentation" cellpadding="0" cellspacing="0"
                        width="100%" border="0">
                        <tbody>
                          <tr>
                            <td class="v-container-padding-padding"
                              style="overflow-wrap:break-word;word-break:break-word;padding:10px 10px 40px;font-family:'Rubik',sans-serif;"
                              align="left">
                              <div class="v-text-align v-line-height"
                                style="color: #000000; line-height: 140%; text-align: center; word-wrap: break-word;">
                                <p style="font-size: 14px; line-height: 140%;">Avenida Universidad #9. Zapata, Morelos
                                  México</p>
                                <p style="font-size: 14px; line-height: 140%;">Equipo de Talenting</p>
                              </div>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</body>

</html>