<!doctype html>
<html lang="en>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Spring Email w/ FreeMarker</title>
</head>
<body>
    <div style="margin-top: 10px">Mensaje de <b>Prueba</b></div>
    <hr/>
    <div>Esta es una <i>Plantilla</i> y tu correito es ${mail.to}</div>
</body>
</html>